# Generated by Django 6.0 on 2026-03-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
